import React,{useEffect,useMemo,useState}from'react';
import{Activity,ArrowLeft,Bell,ChevronRight,CircleDollarSign,Dumbbell,Eye,LayoutDashboard,LogOut,Menu,MessageSquareMore,Plus,Search,Settings,ShoppingBag,Trash2,TrendingUp,UsersRound,X}from'lucide-react';
import'./admin.css';
import CareAdmin from './CareAdmin';
import {api} from './Care';
const call=async(path,options={},token='')=>{const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).message||'Something went wrong.');return r.status===204?null:r.json()};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:0,maximumFractionDigits:2}).format(n||0),date=d=>new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(new Date(d));
function Login({done}){const[error,setError]=useState('');async function submit(e){e.preventDefault();setError('');try{const f=new FormData(e.currentTarget),d=await call('/api/admin/login',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});done(true)}catch(x){setError(x.message)}}return <main className="admin-login"><a href="/"><ArrowLeft/> Back to website</a><section><div className="admin-logo"><Activity/></div><p className="eyebrow">Coach administration</p><h1>Run your coaching<br/><em>business.</em></h1><p>Manage programs, clients, leads and sales from one place.</p><form onSubmit={submit}><label>Email<input name="email" type="email" placeholder="Coach email" required/></label><label>Password<input name="password" type="password" placeholder="Password" required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-btn">Sign in <ChevronRight/></button><small>Use your coach administrator credentials.</small></form></section></main>}
const tabs=[['overview',LayoutDashboard,'Overview'],['programs',Dumbbell,'Programs'],['orders',ShoppingBag,'Orders'],['leads',MessageSquareMore,'Leads'],['clients',UsersRound,'Members'],['physio',Activity,'Post-rehab'],['shifts',TrendingUp,'Transformations'],['settings',Settings,'Settings']];
function Editor({program,close,save}){const[error,setError]=useState('');async function submit(e){e.preventDefault();setError('');const v=Object.fromEntries(new FormData(e.currentTarget));v.features=v.features.split('\n').filter(Boolean);try{await save(v)}catch(e){setError(e.message)}}return <div className="admin-modal-bg"><form className="admin-modal" onSubmit={submit}><button type="button" className="admin-close" onClick={close}><X/></button><p className="eyebrow">{program?'Edit program':'New program'}</p><h2>{program?'Update offer':'Create an offer'}</h2><div className="form-grid"><label>Program title<input name="title" defaultValue={program?.title} required/></label><label>Price (USD)<input name="price" type="number" min="1" step="0.01" defaultValue={program?.price} required/></label><label>Tag<input name="tag" defaultValue={program?.tag||'NEW'}/></label><label>Status<select name="status" defaultValue={program?.status||'draft'}><option value="draft">Draft</option><option value="published">Published</option></select></label><label>Duration<input name="duration" defaultValue={program?.duration||'8 weeks'}/></label><label>Level<input name="level" defaultValue={program?.level||'All levels'}/></label><label className="wide">Subtitle<input name="subtitle" defaultValue={program?.subtitle}/></label><label className="wide">Description<textarea name="description" rows="3" defaultValue={program?.description}/></label><label className="wide">Features (one per line)<textarea name="features" rows="5" defaultValue={program?.features?.join('\n')}/></label><label className="wide">Member-only program instructions<textarea name="content" rows="10" defaultValue={program?.content} placeholder="Training schedule, exercise sets/reps, resources and guidance for assigned members"/></label></div><div role="alert">{error}</div><div className="modal-actions"><button type="button" className="ghost-btn" onClick={close}>Cancel</button><button className="primary-btn">Save program</button></div></form></div>}
export default function Admin(){const[token,setToken]=useState(true), [data,setData]=useState(),[tab,setTab]=useState('overview'),[menu,setMenu]=useState(false),[editor,setEditor]=useState(false),[query,setQuery]=useState(''),[error,setError]=useState(''),[orderFilter,setOrderFilter]=useState('all'),[methodFilter,setMethodFilter]=useState('all'),[inspectedId,setInspectedId]=useState(null),[checkingId,setCheckingId]=useState(null),[providerStatus,setProviderStatus]=useState(null);
 const load=async()=>{try{setData(await call('/api/admin/dashboard',{},token));setError('')}catch(e){setError(e.message);if(/sign in|Access denied/i.test(e.message)){localStorage.removeItem('coach_admin_token');setToken(null)}}};useEffect(()=>{if(token)load()},[token]);useEffect(()=>{if(!token||tab!=='orders')return;const timer=setInterval(load,15000);return()=>clearInterval(timer)},[token,tab]);
 useEffect(()=>{if(tab==='orders')api('/payment-providers').then(setProviderStatus).catch(()=>setProviderStatus(null))},[tab]);
 const list=useMemo(()=>{const q=query.toLowerCase();return{orders:data?.orders.filter(x=>`${x.name} ${x.email} ${x.itemTitle||x.program} ${x.id}`.toLowerCase().includes(q)&&(orderFilter==='all'||x.status===orderFilter)&&(methodFilter==='all'||x.paymentMethod===methodFilter))||[],leads:data?.leads.filter(x=>`${x.name} ${x.email} ${x.goal}`.toLowerCase().includes(q))||[],clients:data?.clients.filter(x=>`${x.name} ${x.program}`.toLowerCase().includes(q))||[]}},[data,query,orderFilter,methodFilter]);
 const save=async(v)=>{await call(editor?.id?`/api/admin/programs/${editor.id}`:'/api/admin/programs',{method:editor?.id?'PUT':'POST',body:JSON.stringify(v)},token);setEditor(false);load()},remove=async id=>{if(confirm('Delete this program?')){try{await call(`/api/admin/programs/${id}`,{method:'DELETE'},token);load()}catch(e){setError(e.message)}}},status=async(type,id,value)=>{try{await call(`/api/admin/${type}/${id}`,{method:'PATCH',body:JSON.stringify({status:value})},token);load()}catch(e){setError(e.message)}},confirmCash=async id=>{if(!confirm('Confirm that the full cash amount was received? This will grant the program or create the paid session request.'))return;try{await call(`/api/admin/orders/${id}`,{method:'PATCH',body:JSON.stringify({confirmCashReceived:true})},token);load()}catch(e){setError(e.message)}};
 const verifyOrder=async id=>{setCheckingId(id);try{await api(`/admin/orders/${id}/verify`,'POST',{});await load()}catch(e){setError(e.message)}finally{setCheckingId(null)}};
 if(!token)return <Login done={setToken}/>;if(!data)return <div className="admin-loading"><Activity/><p>{error||'Loading dashboard…'}</p></div>;
 return <div className="admin-shell"><aside className={menu?'admin-sidebar open':'admin-sidebar'}><a className="admin-brand" href="/"><Activity/><span><b>ANDRE SALEH</b>COACHING OS</span></a><nav>{tabs.map(([id,I,label])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setMenu(false)}}><I/>{label}{id==='leads'&&data.stats.leads>0&&<i>{data.stats.leads}</i>}</button>)}</nav><div className="admin-user"><div>AS</div><span><b>Andre Saleh</b>Head coach</span><button onClick={async()=>{await api('/logout','POST');setToken(null);setData(null)}}><LogOut/></button></div></aside><main className="admin-main"><header className="admin-topbar"><button className="admin-menu" onClick={()=>setMenu(!menu)}><Menu/></button><div><p>{tab}</p><h1>{tab==='overview'?'Good evening, Coach.':tabs.find(x=>x[0]===tab)?.[2]}</h1></div><div className="admin-top-actions"><NotificationBell data={data} load={load}/><a href="/" target="_blank"><Eye/> View website</a><button className="primary-btn" onClick={()=>setEditor({})}><Plus/> Add program</button></div></header>{error&&<div className="admin-alert">{error}</div>}
 {tab==='overview'&&<><section className="stat-grid"><Stat icon={CircleDollarSign} label="Revenue collected" value={money(data.stats.revenue)} note="From paid orders"/><Stat icon={UsersRound} label="Active clients" value={data.stats.clients} note="Registered active members"/><Stat icon={MessageSquareMore} label="New leads" value={data.stats.leads} note="Follow up today"/><Stat icon={Eye} label="Website views" value={data.stats.views.toLocaleString()} note="Page views recorded"/></section><div className="admin-overview-grid"><section className="admin-card"><Head eyebrow="Client health" title="Check-ins at a glance" action={()=>setTab('clients')}/>{data.clients.map(c=><div className="client-row" key={c.id}><Avatar name={c.name}/><div className="client-name"><b>{c.name}</b><span>{c.program}</span></div><div className="compliance"><span>{c.compliance}% compliance</span><i><b style={{width:`${c.compliance}%`}}/></i></div><time>{c.nextCheckIn}</time></div>)}</section><section className="admin-card"><Head eyebrow="Sales" title="Program performance"/>{data.programs.map((p,i)=><div className="sales-row" key={p.id}><span>{i+1}</span><div><b>{p.title}</b><small>{p.sales||0} paid orders</small></div><strong>{money(p.revenue||0)}</strong></div>)}</section></div></>}
 {tab==='programs'&&<section className="admin-card full"><Head eyebrow="Offers" title="Programs & pricing"/>{data.programs.map(p=><article className="program-admin-row" key={p.id}><div className="program-icon"><Dumbbell/></div><div><h3>{p.title}</h3><p>{p.duration} · {p.level}</p></div><span className={`status ${p.status}`}>{p.status}</span><strong>{money(p.price)}</strong><small>{p.sales||0} paid orders</small><button onClick={()=>setEditor(p)}>Edit</button><button className="danger-icon" onClick={()=>remove(p.id)}><Trash2/></button></article>)}</section>}
 {['orders','leads'].includes(tab)&&<section className="admin-card full">
  <div className="table-toolbar"><Head eyebrow="Management" title={tab==='orders'?'Payment activity':tab}/><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tab==='orders'?'Client, item or order reference':`Search ${tab}`}/></label></div>
  {tab==='orders'&&<>
    <div className="payment-provider-status" aria-label="Payment method setup"><span>Cash requests enabled</span>{providerStatus&&<><span>Visa {providerStatus.stripe?.enabled?'configured':'setup required'}</span></>}</div>
    <div className="payment-monitor-summary">
      <div><span>Collected</span><b>{money(data.orders.filter(o=>o.status==='paid').reduce((n,o)=>n+o.amount,0))}</b></div>
      <div><span>Awaiting cash</span><b>{data.orders.filter(o=>o.status==='cash_pending').length}</b></div>
      <div><span>Online pending</span><b>{data.orders.filter(o=>o.status==='awaiting_payment').length}</b></div>
      <div><span>Failed / cancelled</span><b>{data.orders.filter(o=>['failed','cancelled'].includes(o.status)).length}</b></div>
    </div>
    <div className="payment-monitor-filters">
      <label>Payment status<select value={orderFilter} onChange={e=>setOrderFilter(e.target.value)}><option value="all">All statuses</option>{['cash_pending','awaiting_payment','paid','failed','cancelled'].map(x=><option key={x} value={x}>{paymentLabel(x)}</option>)}</select></label>
      <label>Payment method<select value={methodFilter} onChange={e=>setMethodFilter(e.target.value)}><option value="all">All methods</option><option value="cash">Cash</option><option value="online">Online</option></select></label>
      <button className="ghost-btn" onClick={load}>Refresh</button><small>Updates every 15 seconds while this page is open</small>
    </div>
    {!list.orders.length&&<p className="muted">No orders match these filters</p>}
    <Table className="orders-table" headings={['Customer','Program / session','Payment','Date','Amount','Status','Action']}>
      {list.orders.map(o=><div className="tr" key={o.id}><Person x={o}/><span>{o.itemTitle||o.program}{o.requestedAt&&<small>Preferred: {new Date(o.requestedAt).toLocaleString()}</small>}</span><span>{o.paymentMethod==='cash'?'Cash':['whish','stripe'].includes(o.provider)?'Visa / card':'Recorded manually'}</span><span>{date(o.createdAt)}</span><span>{money(o.amount)}</span><span className={`status ${o.status}`}>{paymentLabel(o.status)}</span><span className="payment-row-actions">
        {o.paymentMethod==='cash'&&o.status==='cash_pending'&&<button className="primary-btn" onClick={()=>confirmCash(o.id)}>Confirm cash received</button>}
        {o.status==='awaiting_payment'&&<button disabled={checkingId===o.id} onClick={()=>verifyOrder(o.id)}>{checkingId===o.id?'Checking…':'Check payment'}</button>}
        {['cash_pending','pending'].includes(o.status)&&<button onClick={()=>status('orders',o.id,'cancelled')}>Cancel request</button>}
        <button className="ghost-btn" onClick={()=>setInspectedId(o.id)}>View details</button>
      </span></div>)}
    </Table>
  </>}
  {tab==='leads'&&<Table headings={['Lead','Goal','Source','Date','Status']}>{list.leads.map(l=><div className="tr" key={l.id}><Person x={l}/><span>{l.goal}</span><span>{l.source}</span><span>{date(l.createdAt)}</span><select className={`status ${l.status}`} value={l.status} onChange={e=>status('leads',l.id,e.target.value)}>{['new','contacted','qualified','converted','closed'].map(x=><option key={x}>{x}</option>)}</select></div>)}</Table>}
 </section>}

 {['clients','physio','shifts'].includes(tab)&&<CareAdmin key={tab} data={data} load={load} section={tab}/>}
 {tab==='settings'&&<section className="admin-card full settings-page"><Head eyebrow="Configuration" title="Business settings"/><div className="settings-grid"><Setting icon={Settings} title="Brand & contact" text="Coach identity, email, WhatsApp, social links and colors are centralized in src/config.js."/><Setting icon={CircleDollarSign} title="Online payments" text="Card checkout uses Stripe. Set STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET and your HTTPS APP_ORIGIN in the hosting environment, then configure /api/webhooks/stripe in Stripe. Never paste secret keys into this website. Cash requests stay pending until receipt is confirmed."/><Setting icon={Dumbbell} title="Program delivery" text="Write member-only instructions in the program editor, then assign access from Members."/><Setting icon={TrendingUp} title="Analytics" text="The overview counts page views. Members, check-ins and appointment requests update from your database."/></div></section>}</main>{inspectedId&&<PaymentInspector order={data.orders.find(o=>o.id===inspectedId)} close={()=>setInspectedId(null)}/>} {editor&&<Editor program={editor.id?editor:null} close={()=>setEditor(false)} save={save}/>}</div>}
function NotificationBell({data,load}){const[open,setOpen]=useState(false);const list=data.notifications||[];const unread=data.stats?.unreadNotifications||0;
 return <div className="notif-bell-wrap"><button className="icon-btn notif-bell" aria-label="Payment notifications" onClick={()=>setOpen(!open)}><Bell/>{unread>0&&<i className="notif-badge">{unread}</i>}</button>{open&&<div className="notif-panel"><header><b>Payment activity</b>{unread>0&&<button className="ghost-btn" onClick={async()=>{await api('/admin/notifications/read-all','POST');load()}}>Mark all read</button>}</header>{!list.length&&<p className="muted">No payment activity yet.</p>}{list.slice(0,20).map(n=><div key={n.id} className={'notif-row'+(n.read?'':' unread')} onClick={()=>{if(!n.read){api('/admin/notifications/'+n.id,'PATCH',{});load()}}}><b>{n.memberName}</b> was granted <b>{n.itemTitle}</b><span>${n.amount} · {n.provider} · {new Date(n.createdAt).toLocaleString()}</span></div>)}</div>}</div>}
function Stat({icon:I,label,value,note}){return <article><span><I/></span><p>{label}</p><strong>{value}</strong><small><TrendingUp/>{note}</small></article>}function Head({eyebrow,title,action}){return <div className="card-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action&&<button onClick={action}>View all <ChevronRight/></button>}</div>}function Avatar({name}){return <div className="avatar">{name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div>}function Person({x}){return <span><b>{x.name}</b><small>{x.email}</small></span>}function Table({headings,children,className=''}){return <div className={`data-table ${className}`}><div className="tr th">{headings.map(x=><span key={x}>{x}</span>)}</div>{children}</div>}function Metric({label,value}){return <div className="metric"><span>{label}</span><b>{value}%</b><i><em style={{width:`${value}%`}}/></i></div>}function Setting({icon:I,title,text}){return <article><I/><div><h3>{title}</h3><p>{text}</p></div></article>}

function paymentLabel(status){return {cash_pending:'Awaiting cash',awaiting_payment:'Awaiting online payment',paid:'Paid',failed:'Failed / expired',cancelled:'Cancelled',pending:'Legacy request',refunded:'Refunded'}[status]||status}
function PaymentInspector({order,close}){
 const dialog=React.useRef(null);
 useEffect(()=>{const previous=document.activeElement;dialog.current?.showModal();return()=>{dialog.current?.close();previous?.focus()}},[]);
 if(!order)return null;
 const events=order.events?.length?order.events:[{id:'created',type:'created',label:'Order recorded',createdAt:order.createdAt,actor:'system'}];
 return <dialog ref={dialog} onCancel={close} className="care-dialog payment-inspector" aria-labelledby="payment-detail-title">
  <button className="close-care" aria-label="Close payment details" onClick={close}>×</button>
  <p className="eyebrow">Payment details</p><h2 id="payment-detail-title">{order.itemTitle||order.program}</h2><span className={`status ${order.status}`}>{paymentLabel(order.status)}</span>
  <dl className="payment-detail-fields">
    <div><dt>Client</dt><dd>{order.name}<small>{order.email}</small>{order.phone&&<small>{order.phone}</small>}</dd></div>
    <div><dt>Amount</dt><dd>{money(order.amount)} {order.currency||'USD'}</dd></div>
    <div><dt>Method</dt><dd>{order.paymentMethod==='cash'?'Cash to coach':order.provider==='stripe'?'Visa / Stripe':order.provider||'Manual record'}</dd></div>
    <div><dt>Order reference</dt><dd className="payment-reference">{order.id}</dd></div>
    {order.providerRef&&<div><dt>Provider reference</dt><dd className="payment-reference">{order.providerRef}</dd></div>}
    {order.requestedAt&&<div><dt>Preferred session time</dt><dd>{new Date(order.requestedAt).toLocaleString()}</dd></div>}
    {order.paidAt&&<div><dt>Payment confirmed</dt><dd>{new Date(order.paidAt).toLocaleString()}</dd></div>}
    {order.lastVerificationAttemptAt&&<div><dt>Last verification attempt</dt><dd>{new Date(order.lastVerificationAttemptAt).toLocaleString()}</dd></div>}
    {order.lastVerifiedAt&&<div><dt>Last provider check</dt><dd>{new Date(order.lastVerifiedAt).toLocaleString()}</dd></div>}
    <div><dt>Delivery</dt><dd>{order.fulfilledAt?(order.kind==='service'?'Paid session request created':'Program access granted'):order.status==='paid'?'Recorded as paid':'Access remains locked'}</dd></div>
    {order.notes&&<div><dt>Client note</dt><dd>{order.notes}</dd></div>}
  </dl>
  <h3>Payment timeline</h3><ol className="payment-timeline">{events.map(e=><li key={e.id}><b>{e.label}</b><time>{new Date(e.createdAt).toLocaleString()}</time><small>{e.actor==='coach'?'Coach':e.actor==='member'?'Client':e.actor==='provider'?'Payment provider':'System'}</small></li>)}</ol>
  {!order.events?.length&&<p className="muted">Detailed activity is available for orders created or updated after this release</p>}
 </dialog>
}
